// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OrderSystemAPI.Data;

#nullable disable

namespace OrderSystemAPI.Migrations
{
    [DbContext(typeof(OrderSystemAPIDB))]
    partial class OrderSystemAPIDBModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("OrderSystemAPI.Models.Address", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("AddressType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StreetAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StreetAdress2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ZipCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Address");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            AddressType = "Home",
                            City = "Winlock",
                            State = "WA",
                            StreetAddress = "408 sw Kerron st",
                            ZipCode = "98596"
                        },
                        new
                        {
                            ID = 2,
                            AddressType = "Bussiness",
                            City = "Centralia",
                            State = "WA",
                            StreetAddress = "485 Main st",
                            ZipCode = "98596"
                        },
                        new
                        {
                            ID = 3,
                            AddressType = "Home",
                            City = "Gem",
                            State = "PA",
                            StreetAddress = "626 Alamoa drive",
                            ZipCode = "43254"
                        },
                        new
                        {
                            ID = 4,
                            AddressType = "Home",
                            City = "Jesus",
                            State = "Christ",
                            StreetAddress = "6969 This was hard ave",
                            ZipCode = "78449"
                        });
                });

            modelBuilder.Entity("OrderSystemAPI.Models.Customer", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime>("Birthdate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Customer");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Birthdate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Alys",
                            LastName = "Terwilliger"
                        },
                        new
                        {
                            ID = 2,
                            Birthdate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Jayme",
                            LastName = "Terwilliger"
                        },
                        new
                        {
                            ID = 3,
                            Birthdate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Joe",
                            LastName = "Smith"
                        },
                        new
                        {
                            ID = 4,
                            Birthdate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Angel",
                            LastName = "Smexy"
                        });
                });

            modelBuilder.Entity("OrderSystemAPI.Models.CustomerAddress", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("AddressID")
                        .HasColumnType("int");

                    b.Property<int>("CustomerID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("AddressID");

                    b.HasIndex("CustomerID");

                    b.ToTable("CustomerAddress");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            AddressID = 1,
                            CustomerID = 1
                        },
                        new
                        {
                            ID = 2,
                            AddressID = 2,
                            CustomerID = 2
                        },
                        new
                        {
                            ID = 3,
                            AddressID = 3,
                            CustomerID = 3
                        },
                        new
                        {
                            ID = 4,
                            AddressID = 4,
                            CustomerID = 4
                        });
                });

            modelBuilder.Entity("OrderSystemAPI.Models.Order", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("AddressID")
                        .HasColumnType("int");

                    b.Property<int>("CustomerID")
                        .HasColumnType("int");

                    b.Property<int>("ProductID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            AddressID = 2,
                            CustomerID = 3,
                            ProductID = 1
                        },
                        new
                        {
                            ID = 2,
                            AddressID = 1,
                            CustomerID = 1,
                            ProductID = 2
                        },
                        new
                        {
                            ID = 3,
                            AddressID = 4,
                            CustomerID = 2,
                            ProductID = 1
                        },
                        new
                        {
                            ID = 4,
                            AddressID = 3,
                            CustomerID = 4,
                            ProductID = 4
                        });
                });

            modelBuilder.Entity("OrderSystemAPI.Models.PeoplePhone", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int?>("CustomerID")
                        .HasColumnType("int");

                    b.Property<int>("PeopleID")
                        .HasColumnType("int");

                    b.Property<int>("PhoneNumberID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("CustomerID");

                    b.HasIndex("PhoneNumberID");

                    b.ToTable("PeoplePhone");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            PeopleID = 1,
                            PhoneNumberID = 1
                        },
                        new
                        {
                            ID = 2,
                            PeopleID = 2,
                            PhoneNumberID = 2
                        },
                        new
                        {
                            ID = 3,
                            PeopleID = 3,
                            PhoneNumberID = 3
                        },
                        new
                        {
                            ID = 4,
                            PeopleID = 4,
                            PhoneNumberID = 4
                        });
                });

            modelBuilder.Entity("OrderSystemAPI.Models.PhoneNumber", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("PhoneNumbers");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Number = "3602063171",
                            Type = "Cell"
                        },
                        new
                        {
                            ID = 2,
                            Number = "3605455576",
                            Type = "Cell"
                        },
                        new
                        {
                            ID = 3,
                            Number = "3607854298",
                            Type = "Home"
                        },
                        new
                        {
                            ID = 4,
                            Number = "3214467819",
                            Type = "Cell"
                        });
                });

            modelBuilder.Entity("OrderSystemAPI.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProductStock")
                        .HasColumnType("int");

                    b.Property<string>("color")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Product");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ProductName = "Shirt",
                            ProductStock = 5,
                            color = "Red"
                        },
                        new
                        {
                            Id = 2,
                            ProductName = "Shirt",
                            ProductStock = 2,
                            color = "Blue"
                        },
                        new
                        {
                            Id = 3,
                            ProductName = "Shirt",
                            ProductStock = 5,
                            color = "Black"
                        },
                        new
                        {
                            Id = 4,
                            ProductName = "Pants",
                            ProductStock = 2,
                            color = "Black"
                        },
                        new
                        {
                            Id = 5,
                            ProductName = "Pants",
                            ProductStock = 4,
                            color = "Brown"
                        });
                });

            modelBuilder.Entity("OrderSystemAPI.Models.CustomerAddress", b =>
                {
                    b.HasOne("OrderSystemAPI.Models.Address", "Address")
                        .WithMany()
                        .HasForeignKey("AddressID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OrderSystemAPI.Models.Customer", null)
                        .WithMany("CustomerAddress")
                        .HasForeignKey("CustomerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Address");
                });

            modelBuilder.Entity("OrderSystemAPI.Models.PeoplePhone", b =>
                {
                    b.HasOne("OrderSystemAPI.Models.Customer", null)
                        .WithMany("PhonePhones")
                        .HasForeignKey("CustomerID");

                    b.HasOne("OrderSystemAPI.Models.PhoneNumber", "PhoneNumber")
                        .WithMany()
                        .HasForeignKey("PhoneNumberID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PhoneNumber");
                });

            modelBuilder.Entity("OrderSystemAPI.Models.Customer", b =>
                {
                    b.Navigation("CustomerAddress");

                    b.Navigation("PhonePhones");
                });
#pragma warning restore 612, 618
        }
    }
}
